### ISSUE TITLE
Move from OpenTelemetry Jaeger exporter to OTLP exporter

### ISSUE THREAD

**Issue by ppatierno** [strimzi/test-clients#43]
Referring to this work https://github.com/strimzi/strimzi-kafka-operator/pull/7597 about the Strimzi operator moving from the usage of OpenTelemetry Jaeger exporter to the OTLP exporter, we should do the same for the test-clients.
This is needed because operator is using the test-clients in the `KafkaTracingClients` so corresponding STs for the above PR cannot pass without this change here.
We would need updating the test-clients and a new patch release to be used in that PR to allow STs passing (leaving the main operator branch still using the current test-clients release in order to have all the other operator PRs working fine).

**Comment by im-konge** [comment]
Done in #44
