### ISSUE TITLE
Admin-client: add `if-exists` option to delete a topic

### ISSUE THREAD

**Issue by franvila** [strimzi/test-clients#83]
As part of the development of the Kroxylicious system tests, we have found the need of having an option like [kafka](https://github.com/apache/kafka/blob/5c929874b88b3b96f650de0f733d93d42ac535a4/tools/src/main/java/org/apache/kafka/tools/TopicCommand.java#L796) already have to delete a topic only if it exists and not report and error if don't.

I guess it should be straight forward to add this `--if-exists` option already supported and nothing else need to be done.

**Comment by im-konge** [comment]
Just a note - we are not using these classes inside the admin-client, we are working directly with the Kafka Admin API, which doesn't contain this option.

Anyway, this should be really easy for implementation.

Thanks for raising it :)
