### ISSUE TITLE
Add an optional message key when producing/consuming messages

### ISSUE THREAD

**Issue by franvila** [strimzi/test-clients#90]
In order to fulfill the requirements of this Kroxylicious [PR](https://github.com/kroxylicious/kroxylicious/pull/1180), we would need that test clients include the support of message keys for producing messages and consuming messages.

This message key functionality is already supported by other kafka clients like [kcat](https://github.com/edenhill/kcat) or [kaf](https://github.com/birdayz/kaf).

**Comment by SamBarker** [comment]
Thanks @franvila raising this and the PR to do it has been on my todo list for a while.
